language: node_js
cache: npm
notifications:
  email: false
addons:
  chrome: stable
dist: xenial
services:
  - xvfb
before_script:
  - xvfb-run --server-args="-screen 0 1024x768x24" make test
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
addons:
apt:
install:
  - npm install
script:
  - npm run lint && npm run build:lib && npm run build:docs
node_js:
  - '10'
after_success:
  - ./node_modules/.bin/semantic-release
#   - npm run send-coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: ./dist/docs
  on:
    branch: master
